### ISSUE TITLE
Problems while building functionsimsearch

### ISSUE THREAD

**Issue by whj0401** [googleprojectzero/functionsimsearch#20]
While building functionsimsearch, I met the following error.
```
disassembly/pecodesource.cpp:15:10: fatal error: third_party/pe-parse/pe-parser-library/include/parser-library/parse.h: No such file or directory
 #include "third_party/pe-parse/pe-parser-library/include/parser-library/parse.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [build/pecodesource.o] Error 1
make: *** Waiting for unfinished jobs....
```
I guess the dependency of pe-parse is outdated. Could you provide the correct version? Thanks.

**Comment by In-the-sky** [comment]
I encountered the same problem, do you have a solution?

**Comment by whj0401** [comment]
> I encountered the same problem, do you have a solution?

It is caused by the change of `pe-parser`. The latest version does not have the head file. I remembered I solved it with an older version. see  https://github.com/trailofbits/pe-parse/releases/tag/v1.1.0.rc.2

Hope it can help you.

**Comment by In-the-sky** [comment]
> 

Thank you very much, I will try it now.
